object Versions {
    const val gradlePlugin = "7.2.0"
    const val kotlin = "1.6.21"
    const val hilt = "2.42"
    const val coroutineCore = "1.6.1"
    const val coroutineAndroid = "1.6.1"
    const val gson = "2.8.6"
    const val okHttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val room = "2.4.2"
    const val glide = "4.12.0"
    const val navigation = "2.4.0-alpha01"
    const val lifecycle = "2.3.1"
    const val lifecycleRuntime = "2.4.0-alpha02"
    const val paging = "3.1.1"
    const val ktor = "1.6.0"
}